### ISSUE TITLE
Problem decoding subtitle

### ISSUE THREAD

**Issue by upadrian** [ramiro/service.subtitles.subdivx#3]
```
12:15:30 T:1420817472   ERROR: GetDirectory - Error getting plugin://service.subtitles.subdivx/?action=download&filename=https%3a%2f%2fcs528205.vk.me%2fu202773618%2fvideos%2fc3f2267a0e.720.mp4%3fextra%3dae9hJTYlZwri5cvxJnLGf1tWjYxDv5IJjYrFZiDjmt5bN1UXFHjJ9nVcOQkDd9RL7TDQjz9buRmdwSlEmBinPj7a9pudwQ&id=X6XMTQyNzA4X-criminal-minds-s01e19
12:15:32 T:1395651648  NOTICE: Thread LanguageInvoker start, auto delete: false
12:15:32 T:1395651648  NOTICE: -->Python Interpreter Initialized<--
12:15:33 T:1395651648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.subdivx/service.py", line 531, in <module>
                                                main()
                                              File "/storage/.kodi/addons/service.subtitles.subdivx/service.py", line 510, in main
                                                ensure_workdir(workdir)
                                              File "/storage/.kodi/addons/service.subtitles.subdivx/service.py", line 361, in ensure_workdir
                                                shutil.rmtree(workdir)
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 239, in rmtree
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/posixpath.py", line 69, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)
                                            -->End of Python script error report<--
12:15:33 T:1412428864   ERROR: GetDirectory - Error getting plugin://service.subtitles.subdivx/?action=download&filename=https%3a%2f%2fcs528205.vk.me%2fu202773618%2fvideos%2fc3f2267a0e.720.mp4%3fextra%3dae9hJTYlZwri5cvxJnLGf1tWjYxDv5IJjYrFZiDjmt5bN1UXFHjJ9nVcOQkDd9RL7TDQjz9buRmdwSlEmBinPj7a9pudwQ&id=X6XMTQyNzA4X-criminal-minds-s01e19
```

**Comment by upadrian** [comment]
Sucede solo con algunos subtitulos, imagino que es algo en el nombre del sub.

**Comment by upadrian** [comment]
me olvide de especificar que es sobre openelec raspberry pi 2. Sobre windows funciona bien.

**Comment by ramiro** [comment]
I think this has been fixed or at least worked around in 3c90853c793f6847e2d6f9e2867147661e66d2cb
